// AUTO-GENERATED by opencv-types-generator - do not edit by hand.

import type { CV } from './index';

// Covers `import cv from "opencv.js"` (and similar bundler-driven imports) once both
// packages are installed. If your opencv.js build uses emscripten's MODULARIZE (a factory
// function returning a Promise<CV>) instead of a synchronous default export, adjust this
// declaration to match - see this package's README.
declare module "opencv.js" {
  const cv: CV;
  export default cv;
}
