"""Assembles the final, installable npm project from rendered .d.ts sources."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

from .link_imports import extract_exported_names, find_unresolved_types, inject_imports
from .pipeline import GenerationReport

_PKG_DIR = Path(__file__).parent
_HACKS_DIR = _PKG_DIR / "hacks"
_TEMPLATES_DIR = _PKG_DIR / "templates"

_AUTOGEN_BANNER = "// AUTO-GENERATED by opencv-types-generator - do not edit by hand.\n\n"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _read_template(name: str) -> str:
    return (_TEMPLATES_DIR / name).read_text(encoding="utf-8")


def _hack_stem(path: Path) -> str:
    # Path.stem only strips the *last* suffix, so "scalars.d.ts".stem == "scalars.d" -
    # strip the whole ".d.ts" instead, since every hack file uses that double extension.
    name = path.name
    return name[: -len(".d.ts")] if name.endswith(".d.ts") else path.stem


def emit_package(
    out_dir: str,
    class_files: dict[str, str],
    group_files: dict[str, str],
    report: GenerationReport,
    package_name: str,
    package_version: str,
) -> None:
    out = Path(out_dir)
    if out.exists():
        shutil.rmtree(out)
    generated_dir = out / "generated"
    hacks_dir = out / "hacks"
    generated_dir.mkdir(parents=True)
    hacks_dir.mkdir(parents=True)

    # Deterministic tie-break: a group compound whose file stem collides with an
    # already-written class name (rare, but possible - doxygen group titles and class
    # names live in different namespaces) gets a `group_` prefix instead of clobbering
    # the class file.
    final_stems: dict[str, str] = {}  # original stem -> final stem, generated files only
    for stem in class_files:
        final_stems[("class", stem)] = stem
    used = set(class_files)
    for stem in group_files:
        final_stems[("group", stem)] = f"group_{stem}" if stem in used else stem
        used.add(final_stems[("group", stem)])

    # Pass 1: read every hack file's own exports (hand-written, own imports already
    # correct) and every generated file's exports, to build a global symbol -> module map
    # before injecting a single import - a file can reference a symbol declared in a file
    # we haven't rendered yet in iteration order.
    export_index: dict[str, str] = {}
    hack_sources: dict[str, str] = {}
    for hack_file in sorted(_HACKS_DIR.glob("*.d.ts")):
        text = hack_file.read_text(encoding="utf-8")
        stem = _hack_stem(hack_file)
        hack_sources[stem] = text
        for name in extract_exported_names(text):
            export_index[name] = f"../hacks/{stem}"
    generated_contents: dict[str, str] = {}  # final_stem -> content, generated files only
    for (kind, stem), final_stem in final_stems.items():
        content = class_files[stem] if kind == "class" else group_files[stem]
        generated_contents[final_stem] = content
        for name in extract_exported_names(content):
            export_index[name] = f"./{final_stem}"

    # Anything referenced but neither one of ours nor a known DOM/ES global is a genuine
    # gap (a C++-only type opencv.js never binds, e.g. `Matx`/`Point_`/`MatIterator_`) -
    # stub it to `any` in one file and register it, rather than leave a hard compile error.
    unresolved = find_unresolved_types(list(generated_contents.values()), export_index)
    if unresolved:
        stub_src = "\n".join(f"export type {name} = any;" for name in sorted(unresolved))
        _write(
            generated_dir / "_unresolved.d.ts",
            _AUTOGEN_BANNER
            + "// Referenced by generated types but not produced by opencv.js's own\n"
            + "// bindings for this build (template/internal-only C++ types, mainly) -\n"
            + "// see generation-report.json's `unresolved_types`.\n\n"
            + stub_src
            + "\n",
        )
        for name in unresolved:
            export_index[name] = "./_unresolved"

    # Pass 2: write generated files with imports injected, and copy hacks verbatim.
    module_paths: list[str] = []
    for final_stem, content in generated_contents.items():
        content = inject_imports(content, own_name=final_stem, export_index=export_index)
        _write(generated_dir / f"{final_stem}.d.ts", _AUTOGEN_BANNER + content + "\n")
        module_paths.append(f"./generated/{final_stem}")

    hack_stems = list(hack_sources)
    for hack_file in sorted(_HACKS_DIR.glob("*.d.ts")):
        shutil.copy(hack_file, hacks_dir / hack_file.name)

    report.unresolved_types = sorted(unresolved)
    barrel_lines = [f"export * from '{p}';" for p in module_paths]
    barrel_lines += [f"export * from './hacks/{stem}';" for stem in hack_stems]
    _write(out / "_barrel.d.ts", _AUTOGEN_BANNER + "\n".join(barrel_lines) + "\n")

    _write(out / "index.d.ts", _AUTOGEN_BANNER + _INDEX_DTS)
    _write(out / "opencv.js.d.ts", _AUTOGEN_BANNER + _MODULE_AUGMENTATION_DTS)

    package_json = _read_template("package.json.tmpl").replace("{{name}}", package_name).replace(
        "{{version}}", package_version
    )
    _write(out / "package.json", package_json)
    _write(out / "tsconfig.json", _read_template("tsconfig.json.tmpl"))
    _write(out / "generation-report.json", json.dumps(report.to_dict(), indent=2) + "\n")
    _write(out / "README.md", _readme(package_name))
    _write(out / "LICENSE", _LICENSE)
    _write(out / ".gitignore", _read_template("gitignore.tmpl"))

    _write(out / "smoke-test" / "index.ts", _read_template("smoke-test.ts.tmpl"))
    _write(out / "smoke-test" / "tsconfig.json", _read_template("smoke-test.tsconfig.json.tmpl"))
    _write(out / "smoke-test" / "tsconfig.node.json", _read_template("smoke-test.tsconfig.node.json.tmpl"))


_INDEX_DTS = """\
export * from './_barrel';

import * as _CV from './_barrel';

export type CV = typeof _CV;

declare global {
  var cv: CV;
}
"""

_MODULE_AUGMENTATION_DTS = """\
import type { CV } from './index';

// Covers `import cv from "opencv.js"` (and similar bundler-driven imports) once both
// packages are installed. If your opencv.js build uses emscripten's MODULARIZE (a factory
// function returning a Promise<CV>) instead of a synchronous default export, adjust this
// declaration to match - see this package's README.
declare module "opencv.js" {
  const cv: CV;
  export default cv;
}
"""

_LICENSE = """\
MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


def _readme(package_name: str) -> str:
    return f"""\
# {package_name}

Community TypeScript type declarations for [opencv.js](https://docs.opencv.org/5.0/js_tutorials/js_tutorials.html),
generated from OpenCV's own doxygen XML API docs cross-referenced against the
`bindings.cpp` file its build produces (the source of truth for what's actually exposed
on the `cv` object at runtime) - see
[opencv-types-generator](https://github.com/) for the generator itself.

## Install

```sh
npm install {package_name} opencv.js
```

## Usage

**Ambient global** (`<script src="opencv.js"></script>` + `cv.onRuntimeInitialized`):

```ts
import "{package_name}"; // side-effect import: brings the ambient `cv` global into scope

cv.onRuntimeInitialized = () => {{
  const mat = new cv.Mat();
  // ...
}};
```

**Module import** (bundler-driven `opencv.js` load):

```ts
import cv from "opencv.js";

const mat = new cv.Mat();
```

If your bundler/tsconfig doesn't pick up the ambient global declarations automatically,
add this package to your `tsconfig.json`'s `compilerOptions.types` array, or add a single
`import "{package_name}";` somewhere in your program's entry point.

## Coverage

Not every OpenCV API makes it into these types - only what OpenCV's own opencv.js build
actually registers via embind is generated. `generation-report.json` (shipped in this
package) lists every `bindings.cpp` registration that had no matching doxygen XML node for
this particular build, if you're missing something.

## License

MIT
"""
